
version: '3.8'
services:
  telegram-bot:
    build: ../
    container_name: telegram-bot
    env_file:
      - telegram-bot.env
    volumes:
      - /var/log/telegram-bot/logs:/tmp
    restart: always
